name: "Setup Nextflow"
description: |
  Install Nextflow and its dependencies into a GitHub Actions environment, cache
  the installation, and add it to the PATH
author: "nf-core"
inputs:
  version:
    description: "The Nextflow version to download (if necessary) and use. Example: 21.10.3"
    required: false
    default: "stable"
  java-version:
    description: "The Java version to install as the required dependency of Nextflow. Passed to the underlying setup-java action."
    required: false
    default: ""
  java-distribution:
    description: "The Java distribution to install as the required dependency of Nextflow. Passed to the underlying setup-java action."
    required: false
    default: "temurin"
  secrets:
    description: "Nextflow secrets to set, in KEY=VALUE format (one per line). See README for usage."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: ./subactions/find-nextflow-version
      id: find-nextflow-version
      with:
        version: ${{ inputs.version }}
        java-version: ${{ inputs.java-version }}
        token: ${{ github.token }}
    - uses: actions/setup-java@1d018f9b8b9b505bb578a83b230fabcce01af93b
      id: install-java
      with:
        java-version: ${{ steps.find-nextflow-version.outputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
    - uses: ./subactions/install-nextflow
      id: install-nextflow
      with:
        version: ${{ steps.find-nextflow-version.outputs.nextflow-version }}
    - uses: ./subactions/add-secrets
      id: add-secrets
      with:
        path: ${{ steps.install-nextflow.outputs.path }}
        secrets: ${{ inputs.secrets }}
branding:
  icon: "shuffle"
  color: "green"
