name: Example builds

on:
  push:
    branches:
      - master
      # https://docs.renovatebot.com/key-concepts/automerge/#branch-vs-pr-automerging
      - "renovate/**" # branches Renovate creates
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  example-usage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nextflow_version:
          - "stable"
          - "edge"
          - "18.10.1" # This is the oldest version we support
          - "24.10.6" # This is on one side of the Java version switch
          - "24.11.0-edge" # This is on the other side

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./
        with:
          version: ${{ matrix.nextflow_version }}
      - run: nextflow -v

  example-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./
        with:
          version: "stable"
          secrets: |
            MY_TEST_SECRET=hello_world
            ANOTHER_SECRET=foo_bar
      - name: Verify secrets were set
        run: |
          [[ "$(nextflow secrets get MY_TEST_SECRET)" == "hello_world" ]]
          [[ "$(nextflow secrets get ANOTHER_SECRET)" == "foo_bar" ]]

  example-maximized-build-space:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # v10
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./
      - run: nextflow -v
