name: Example builds

on:
  push:
    branches:
      - master
      # https://docs.renovatebot.com/key-concepts/automerge/#branch-vs-pr-automerging
      - "renovate/**" # branches Renovate creates
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  example-usage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nextflow_version:
          - "21.10.3"
          - "22.04"
          - "22.03.1-edge"
          - "24.10.1"
          - "latest"
          - "latest-stable"
          - "latest-edge"
          - "latest-everything"
        all_distribution:
          - true
          - false

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run package
      - uses: ./
        with:
          version: ${{ matrix.nextflow_version }}
          all: ${{ matrix.all_distribution }}
      - run: nextflow -v

  example-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run package
      - uses: ./
        with:
          version: "latest-stable"
          secrets: |
            MY_TEST_SECRET=hello_world
            ANOTHER_SECRET=foo_bar
      - name: Verify secrets were set
        run: |
          [[ "$(nextflow secrets get MY_TEST_SECRET)" == "hello_world" ]]
          [[ "$(nextflow secrets get ANOTHER_SECRET)" == "foo_bar" ]]

  example-maximized-build-space:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # v10
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run package
      - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
        if: ${{ env.ACT}}
        with:
          java-version: 21
          distribution: temurin
      - uses: ./
      - run: nextflow -v
